name: Build Binaries

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build-jvm:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with: { java-version: '21', distribution: 'temurin' }

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Compile to Jar
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with: { path: build/libs/* , name: "kt-encabulator-jvm" }

  build-native:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { os: "windows-latest", suffix: "-win"}
          - { os: "ubuntu-latest",  suffix: "-linux" }

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with: { java-version: '21', distribution: 'graalvm' }

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Compile to Native Binary
        run: ./gradlew nativeCompile

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/native/nativeCompile/kt-encabulator*
          name: "kt-encabulator${{ matrix.suffix }}"